# Generated by Django 4.2.5 on 2023-10-15 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_cartitems_price_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='price',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
