# Generated by Django 4.2.5 on 2023-10-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_cartitems_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='price',
        ),
        migrations.AddField(
            model_name='cartitems',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
