# Generated by Django 4.2.6 on 2023-10-21 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.cartitems'),
        ),
    ]
