# Generated by Django 4.2.5 on 2023-10-12 16:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('user_message', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
